### PR TITLE
Delete old, obsolete, broken and unused code

### PR DESCRIPTION
**Pull request by lishaduck**
## Description

This PR deletes vestiges we keep stepping on.

_**Closes**: #21_

---

## Type of Change

- 🔥 Remove obsolete, unused things

## Checklist

- [x] Read the Contributing Guidelines.
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Fill out this template.
- [ ] Log your hours.
- [x] Check that commits follow the Angular commit convention, more or less.
- [ ] Ideally, include relevant tests that fail without this PR but pass with it (if applicable).

## Tested on

- CI

### CODE REVIEW

**Comment by lishaduck** [comment]
@MattsAttack, I'd still like a review here, despite merging it.

**Review by MattsAttack — COMMENTED** [review]
Found one bug:
AppwriteException (AppwriteException: general_unauthorized_scope, User (role: guests) missing scope (account) (401)) (When pressing the log out button)

I believe this is due to the app immediatley routing the user to the router page even if they are not logged in.  I'm assuming this means there's some issue with the route guards that's not checking if the user is logged in before showing the wrapper page

**Comment by lishaduck** [comment]
Wish I'd seen this before I closed vs code for the night...
Can you share a screenshot?

**Comment by MattsAttack** [comment]
Yeah. Let me open the work tree back up and see if I can get it to show again. It only happens when you first open the app and try to log out. If you reopen the app you're sent to the login page.

**Comment by MattsAttack** [comment]
I tried to recreate the bug but haven't been able to. We should look into it more when we're polishing the app for TSA but I wouldn't worry about it now

**Pull request merged**
