### PR TITLE
Posts

### PR DESCRIPTION
**Pull request by lishaduck**
## Description

This PR implements posting stuff.

Needs #3 & probably @MattsAttack's work on Auth (Appwrite code).

---

## Type of Change

- ✨ New feature

## Checklist

```[tasklist]
### Checklist
- [x] Read the Contributing Guidelines.
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Fill out this template.
- [ ] Log your hours.
- [x] Check that commits follow the Angular commit convention, more or less.
- [x] Ideally, include relevant tests that fail without this PR but pass with it (if applicable).
```

## Tested on

- macOS 14

### CODE REVIEW

**Comment by lishaduck** [comment]
@MattsAttack, could you please confirm that your posts branch fully supersedes this, and, if so, close this and replace it with a draft PR.

**Comment by MattsAttack** [comment]
My bad, I had to read a 34 page paper about quantum computing for english. I'll review this and see if I missed anything.

**Comment by lishaduck** [comment]
I feel ya, I'm working through webassigns as I wait for these CI runs to run.

**Comment by MattsAttack** [comment]
@lishaduck I added everything to create-posts except for the save and like button code. I'll go and add that real quick.

**Comment by lishaduck** [comment]
> @lishaduck I added everything to create-posts except for the save and like button code. I'll go and add that real quick.

The like button code was mostly a joke. Probably add it, but do know it doesn't render right yet.

**Comment by MattsAttack** [comment]
> I feel ya, I'm working through webassigns as I wait for these CI runs to run. 
If my calc test doesn't get moved to Monday I'm so cooked. Each webassign takes like 2 hours and I have like 6.5/10 of them done. The teachers ok with moving it to Monday but some of the kids who already took calc AB are whining about it and would rather take it on Friday.

**Comment by lishaduck** [comment]
It's really funny that we're chatting on a PR 🤣

**Comment by MattsAttack** [comment]
if it works it works

**Comment by MattsAttack** [comment]
I added the like and save code to create-posts. My home pc is still having issues with the api for some reason though. I have the correct .env file to so idk what the problem is

**Comment by lishaduck** [comment]
> My home pc is still having issues with the api for some reason though. I have the correct .env file to so idk what the problem is

Sounds good, can you PR? We can debug it tomorrow. (did you rerun codegen?)

**Comment by MattsAttack** [comment]
Yes, everything compiles it's just not communicating with appwrite for some unknown reason

**Comment by lishaduck** [comment]
Superseded by #31.

**Pull request closed without merging**
